[platformio]
default_envs = crowpanel_579

[env:crowpanel_579]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
build_flags =
  -D BOARD_HAS_PSRAM
lib_deps =
  zinggjm/GxEPD2@1.6.9
  bblanchon/ArduinoJson@7.4.2

